// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "components": {
    "i18n": {
      "localizationSelect": {
        "label": "label",
        "placeholder": "placeholder"
      }
    }
  },
  "index": {
    "card": {
      "description": "Choose flow",
      "title": "User flows"
    },
    "flows": {
      "login": "Login"
    },
    "metadata": {
      "description": "kratos user flows introduction",
      "title": "Flows"
    }
  },
  "login-flow": {
    "metadata": {
      "description": "Login user flow",
      "title": "Login"
    }
  }
}

export default Resources;
