// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "index": {
    "description": "description",
    "title": "title"
  },
  "lng": {
    "hello-world": "Hello World!"
  }
}

export default Resources;
